name: OriginsRebornRoleplay
main: io.starseed.orp.OriginsRebornRoleplay
version: 1.0
api-version: 1.21
author: Starseed
description: A roleplay plugin for managing player characters and integrating with Discord and PlaceholderAPI.

commands:
  rpprofile:
    description: View your roleplay profile.
    usage: /rpprofile
    permission: originsreborn.profile.view
  newcharacter:
    description: Create a new character.
    usage: /newcharacter <name>
    permission: originsreborn.character.create
  characters:
    description: List your characters.
    usage: /characters
    permission: originsreborn.character.list
  delcharacter:
    description: Delete a character.
    usage: /delcharacter <name>
    permission: originsreborn.character.delete
  character:
    description: Select or view a character
    usage: /character [name]
  editcharacter: # Add this section
    description: Edit a character's field.
    usage: /editcharacter <name> <field>


permissions:
  originsreborn.profile.view:
    description: Allows the player to view their roleplay profile.
    default: true
  originsreborn.character.create:
    description: Allows the player to create a new character.
    default: true
  originsreborn.character.list:
    description: Allows the player to list their characters.
    default: true
  originsreborn.character.delete:
    description: Allows the player to delete a character.
    default: true
  originsreborn.character.edit:
    description: Allows the player to edit a character's field.
    default: true

depend:
  - PlaceholderAPI