database:
  host: your_database_host
  name: your_database_name
  username: your_database_username
  password: your_database_password
  port: 3306

discord:
  webhook-url: your_discord_webhook_url

limits:

  max-characters: 300